### [예제 9] np.random.shuffle() 리뷰 및 실습

In [2]:
import numpy as np

In [3]:
A = np.array([ data for data in range(6)  ])

print(A)
print(type(A), A.shape)

[0 1 2 3 4 5]
<class 'numpy.ndarray'> (6,)


In [4]:
np.random.shuffle(A)

print(A)
print(type(A), A.shape)

[3 4 1 5 2 0]
<class 'numpy.ndarray'> (6,)


In [5]:
B = np.array([ [data, data] for data in range(4) ])

print(B)
print(type(B), B.shape)

[[0 0]
 [1 1]
 [2 2]
 [3 3]]
<class 'numpy.ndarray'> (4, 2)


In [7]:
np.random.shuffle(B)

print(B)
print(type(B), B.shape)

[[0 0]
 [2 2]
 [3 3]
 [1 1]]
<class 'numpy.ndarray'> (4, 2)
