### [예제 2.2]

In [0]:
# 입력변수 2 개인 함수 f(x, y) = 2x + 3xy + y^3
def func2(W):    
    
    x = W[0]
    y = W[1] 
    
    return  ( 2*x + 3*x*y + np.power(y,3) )   

# lambda function 정의
f = lambda W : func2(W)

# (x,y) = (1.0, 2.0) 에서의 편미분 값
W = np.array([1.0, 2.0]) 

numerical_derivative( f, W ) 

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
debug 4. grad[idx] =  8.00000000005241
debug 5. grad =  [8. 0.]
debug 3. idx =  (1,) , x[idx] =  2.0
debug 4. grad[idx] =  15.000000000142675
debug 5. grad =  [ 8. 15.]


array([ 8., 15.])

### [예제 2.3]

In [0]:
# 입력변수 4 개인 함수 
# f(w,x,y,z) = wx + xyz + 3w + zy^2
# input_data 는 행렬

def func(input_data):    
    
    w = input_data[0, 0]
    x = input_data[0, 1] 
    y = input_data[1, 0]
    z = input_data[1, 1] 
    
    return  ( w*x + x*y*z + 3*w + z*np.power(y,2) )   

# lambda function 정의
f = lambda W : func(W)

# 입력을 2X2 행렬로 구성함
input_data = np.array([ [1.0, 2.0], [3.0, 4.0] ]) 

ret = numerical_derivative( f, input_data ) 

print(ret)

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
debug 4. grad[idx] =  5.000000000165983
debug 5. grad =  [[5. 0.]
 [0. 0.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
debug 4. grad[idx] =  12.99999999986312
debug 5. grad =  [[ 5. 13.]
 [ 0.  0.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
debug 4. grad[idx] =  32.00000000020964
debug 5. grad =  [[ 5. 13.]
 [32.  0.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
debug 4. grad[idx] =  14.999999999787404
debug 5. grad =  [[ 5. 13.]
 [32. 15.]]
[[ 5. 13.]
 [32. 15.]]


### [예제 2.4]  미분변수 값이 정수와 실수인 경우
#### numerical_derivative(...) 디버그 문장 세분화

In [0]:
import numpy as np

def numerical_derivative(f, x):    # 수치미분 debug version
    delta_x = 1e-4 
    grad = np.zeros_like(x)
    
    print('debug 0. type(grad) = ', type(grad))
    print("debug 1. initial input variable =", x)   
    print("debug 2. initial grad =", grad) 
    print("=======================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ", x[idx])   
        
        tmp_val = x[idx]
        
        # x[idx] 변수가 정수타입이면 계산값이 타입캐스팅되어,
        # 즉 소수점 아래부분은 버려져서 x[idx] 에 대입됨
        x[idx] = float(tmp_val) + delta_x   
        
        print("debug 4. x[idx] = ", x[idx])
        
        fx1 = f(x)   # f(x+delta_x)
        
        print("debug 5. fx1 = ", fx1)
        
        # x[idx] 변수가 정수타입이면 계산값이 타입캐스팅되어,
        # 즉 소수점 아래부분은 버려져서 x[idx] 에 대입됨
        x[idx] = float(tmp_val) - delta_x 
        
        print("debug 6. x[idx] = ", x[idx])
        
        fx2 = f(x)   # f(x-delta_x)
        
        print("debug 7. fx2 = ", fx2)
        
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print('debug 8. grad[idx] = ', grad[idx])
        print("debug 9. grad = ", grad) 
        print("=======================================")
        
        x[idx] = tmp_val
        it.iternext()   
        
    return grad

#### 입력데이터가 실수가 아닌 경우 

In [0]:
# 입력변수 1 개인 함수 f(x) = x**2
def func1(W):    
    
    x = W[0]
    
    return  x**2  

f = lambda W : func1(W)

# 실수가 아닌 정수값 3을 입력하는 경우 예제
W = np.array([3])

# x = 3 에서의 편미분 값
numerical_derivative( f, W ) 

debug 0. type(grad) =  <class 'numpy.ndarray'>
debug 1. initial input variable = [3]
debug 2. initial grad = [0]
debug 3. idx =  (0,) , x[idx] =  3
debug 4. x[idx] =  3
debug 5. fx1 =  9
debug 6. x[idx] =  2
debug 7. fx2 =  4
debug 8. grad[idx] =  25000
debug 9. grad =  [25000]


array([25000])

#### 입력데이터가 실수인 경우

In [0]:
# 입력변수 1 개인 함수 f(x) = x**2
def func1(W):    
    
    x = W[0]
    
    return  x**2  

f = lambda W : func1(W)

# 실수값 3.0을 입력하는 경우 예제
W = np.array([3.0])

# x = 3.0 에서의 편미분 값
numerical_derivative( f, W ) 

debug 0. type(grad) =  <class 'numpy.ndarray'>
debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
debug 4. x[idx] =  3.0001
debug 5. fx1 =  9.000600010000001
debug 6. x[idx] =  2.9999
debug 7. fx2 =  8.999400009999999
debug 8. grad[idx] =  6.000000000012662
debug 9. grad =  [6.]


array([6.])