### [예제 1.1]

In [4]:
A = np.array([1, 2])
B = np.array([3, 4])
T = np.array([5, 6])

print(A.shape)
print(B.shape)

print((1-A)*A)
print(T*(1-A)*A)

(2,)
(2,)
[ 0 -2]
[  0 -12]


### [예제 1.2]

In [5]:
C = np.array([ [2], [3] ])
D = np.array([ [4], [5] ])
T = np.array([ [7], [8] ])

print(C.shape)
print(D.shape)

print((1-C)*C)
print(T*(1-C)*C)

(2, 1)
(2, 1)
[[-2]
 [-6]]
[[-14]
 [-48]]


### [예제 1.3]

In [6]:
X = np.array([ [1,2], [3,4] ])
W = np.array([ [0,1,1], [3,2,1] ])
T = np.array([ [1,0], [0,2] ])
b = -1

In [7]:
Y = np.dot(X, W) + b

print(Y)

[[ 5  4  2]
 [11 10  6]]


In [8]:
E = T - Y

print(E)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

### [예제 1.4]

In [9]:
A = np.array([ [1, 2, 3], [4, 5, 6] ])

B = np.array([10, 20, 30])

C = A.T

D = np.dot(C, B)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)