### [예제 2.1]

In [23]:
import numpy as np

# index 이용하여 넘파이 원소값 출력
def func1(var):
    
    if var.ndim == 1:    # vector
        
        for index in range(len(var)):
            
            print('value = ', var[index])
            
    elif var.ndim == 2:  # matrix
        
        rows = var.shape[0]
        columns = var.shape[1]
        
        for row in range(rows):
            for column in range(columns):
                
                print('value = ', var[row, column])
                
    else:
        
        print('not support tensor...')

In [34]:
# iterator 이용하여 넘파이 원소값 출력
def func2(var):
    
    it = np.nditer(var, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        
        index = it.multi_index
        
        print('value = ', var[index])
        #print('index = ', index, ', value = ', var[index])
        
        it.iternext()

In [35]:
X1 = np.array([1, 2, 3, 4, 5])  # vector
X2 = np.array([ [2, 4], [1, 2], [0, 5] ])  # matrix
X3 = np.array([ [ [2, 4], [1, 2] ], [ [3, 5], [6, 8] ] ])  # tensor

In [36]:
# vector X1 에 대한 func1, func2 호출

func1(X1)
print('==============')
func2(X1)

value =  1
value =  2
value =  3
value =  4
value =  5
value =  1
value =  2
value =  3
value =  4
value =  5


In [37]:
# matrix X2 에 대한 func1, func2 호출

func1(X2)
print('==============')
func2(X2)

value =  2
value =  4
value =  1
value =  2
value =  0
value =  5
value =  2
value =  4
value =  1
value =  2
value =  0
value =  5


In [38]:
# tensor X3 에 대한 func1, func2 호출

func1(X3)
print('==============')
func2(X3)

not support tensor...
value =  2
value =  4
value =  1
value =  2
value =  3
value =  5
value =  6
value =  8


### [예제 2.2]

In [39]:
X = np.array([ [7, 5, 3, 1], [1, 2, 3, 4], [4, 0, 2, 8] ])

X.shape

(3, 4)

In [40]:
A = X.reshape(-1, 3)

A

array([[7, 5, 3],
       [1, 1, 2],
       [3, 4, 4],
       [0, 2, 8]])

In [41]:
B = A[0:2, 1:2]

B

array([[5],
       [1]])

In [42]:
C = A[1:, :-1]

C

array([[1, 1],
       [3, 4],
       [0, 2]])

In [43]:
D = np.argmax(A, 1)

D

array([0, 2, 1, 2], dtype=int64)

In [44]:
E = C.reshape(-1,6)

E

array([[1, 1, 3, 4, 0, 2]])

In [45]:
F = np.sum(E)

F

11

In [46]:
G = np.log(X)

G

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[1.94591015, 1.60943791, 1.09861229, 0.        ],
       [0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.38629436,       -inf, 0.69314718, 2.07944154]])

In [52]:
delta = 1e-8  # 실행 컴퓨터가 저사양이라면 1e-5 정도로 해주는것이 좋음. 즉 delta를 너무 낮게 하면 호환성 및 정밀도 문제 발생

G_1 = np.log(X+delta)

G_1

array([[ 1.94591015e+00,  1.60943791e+00,  1.09861229e+00,
         9.99999989e-09],
       [ 9.99999989e-09,  6.93147186e-01,  1.09861229e+00,
         1.38629436e+00],
       [ 1.38629436e+00, -1.84206807e+01,  6.93147186e-01,
         2.07944154e+00]])

### [예제 2.3]

In [1]:
import numpy as np

In [9]:
W = np.random.rand(1,1)
b = np.random.rand(1)

print(W, b)

[[0.24310629]] [0.57688472]


In [12]:
def loss_func(xdata, tdata):
    
    y = np.dot(xdata, W) + b
    
    loss = np.sum((tdata-y)**2) / (len(xdata))
    
    return loss

In [13]:
xdata = np.array([1, 2, 3, 4, 5]).reshape(5,1)
tdata = np.array([3, 4, 5, 6, 7]).reshape(5,1)

ret = loss_func(xdata, tdata)

print('ret = ', ret)

ret =  14.789908136945593
