### [예제 6] Softmax 개념 및 기본구현

In [1]:
import numpy as np

In [2]:
def softmax(a):
    
    numerator = np.exp(a)
    denominator = np.sum(np.exp(a))
    
    y = numerator / denominator
    
    return y

In [3]:
A = np.array([0.7 ,  0.8  ,  0.01])

B = np.array([0.3  , 2.9,  4.0])

C = np.array([110 ,  100 ,  90])

D = np.array([1000, 1100, 900])

In [4]:
print(softmax(A))
print(softmax(B))
print(softmax(C))
print(softmax(D))

[0.38361989 0.42396555 0.19241456]
[0.01821127 0.24519181 0.73659691]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]
[nan nan nan]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
